### ISSUE TITLE
The order of Props and State in inconsistent between the readme and the code

### ISSUE THREAD

**Issue by CruseCtrl** [Dean177/with-url-state#141]
In the readme we have the following line:
```typescript
const enhance = withUrlState<OwnProps, UrlState>((prop: OwnProps) => ({ color: 'blue' }))
```

But in `/src/withUrlState.ts` we have
```typescript
export const withUrlState = <T extends object, OP>(
  getInitialState: (props: OP) => T,
```

`getInitialState` maps the props to the state, so `OP` is the `Props` and `T` is the `State`

It would be nicest to swap the order of the props, so that it can be used with `withUrlState<UrlState, OwnProps>` to match the order of a standard React component. But since that would break a few builds, the readme should at least be updated to reflect this.

**Comment by Dean177** [comment]
If you submit a PR for just the readme that would be great. Still undecided about the type parameter order.

**Comment by CharlesRea** [comment]
I'm inclined to agree with Dean, there isn't really any convention about ordering of generic types for higher order components - there are good arguments for either way here.

I don't think that's a strong enough reason to make a breaking change here, so I think it'd be worth sticking with how it already works.
