### ISSUE TITLE
Hooks?

### ISSUE THREAD

**Issue by CharlesRea** [Dean177/with-url-state#142]
Any chance the v3 branch could be released if it's ready to go?

Cheers

**Comment by Dean177** [comment]
Its published on npm as an alpha: `3.0.0-alpha.2`.

**Comment by CharlesRea** [comment]
Ah, somehow missed that when I'd looked earlier, cheers.

**Comment by Dean177** [comment]
No worries, if you don't encounter any issues I will release it.
