### ISSUE TITLE
Getting "window is not defined" when using custom history on SSR application

### ISSUE THREAD

**Issue by Henriquelange** [Dean177/with-url-state#144]
I'm instantiating a new withUrlState component using a custom history inside the config parameter, [as described on the changelog](https://github.com/Dean177/with-url-state/blob/master/CHANGELOG.md).

The application has a NextJS SSR implementation, though not supporting browser components. When the method executes, it throws the following:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/node_modules/with-url-state/dist/withUrlState.js:24:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.with-url-state (/.next/dist/bundles/pages/_error.js:53158:18)
```

As I checked, apparently this error is being thrown because the html5HistoryAdapter _location_ property export calls window.location independently of the config object passed on the constructor:

```
exports.html5HistoryAdapter = {
    listen: function (listener) {
        window.addEventListener('popstate', listener);
        return function () { return window.removeEventListener('popstate', listener); };
    },
    location: window.location,
    push: function (_a) {
        var search = _a.search;
        window.history.pushState(window.history.state, document.title, search);
        window.dispatchEvent(new window.Event('popstate'));
    },
    replace: function (_a) {
        var search = _a.search;
        window.history.replaceState(window.history.state, document.title, search);
        window.dispatchEvent(new window.Event('popstate'));
    },
};
```

Could you, please, take a look at this?

**Comment by Dean177** [comment]
Looks like this is due to the location property, its the only call not wrapped in a function. 
I think the simplest thing to do would be to change:
```
export type HistoryAdapter = {
  location: ...
  ...
}
```
to 
```
export type HistoryAdapter = () => {
  location: ...
  ...
}
```
And adding a few function calls into the implementation where necessary.

Are you up for creating a PR?
