### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by newyork-anthonyng** [Dean177/with-url-state#42]
Thank you for this project 👍 

I wanted to play around with the demo and noticed the link was broken (https://dean177.github.io/with-url-state/).

I'm wondering if including a [CodeSandbox](codesandbox.io) example would be helpful as well. This way, users can edit the code and play around with it as well.

I could create a CodeSandbox with the example from this repository. Let me know what you think; I can create a Pull Request to include it in the `README.md`.

**Comment by Dean177** [comment]
Thanks for the issue @newyork-anthonyng. Hopefully the demo link should be back. Creating a CodeSandbox would be great, let me know if you encounter any issues with the library setting it up.
