### ISSUE TITLE
Warn the users who have sensitive info in their state

### ISSUE THREAD

**Issue by userpixel** [Dean177/with-url-state#44]
Good job. Just a security concern:

Redux promotes single state and ask too often people store sensitive info like credentials or tokens in it. There needs to be a way to opt-out part of the state or opt-in relevant parts. A reducer that takes state and generates JSON for this lib can do both.
Nevertheless it's good to warm the users of this lib puts the whole state in the url.

**Comment by Dean177** [comment]
Hi and thanks @userpixel. 

I agree that you will want to be quite selective about which state you are storing with this. 

I think that typically this is something that would be used along side Redux and only for some very specific parts of your application:
The use-cases which led to me writing this were things like [search boxes](https://github.com/Dean177/with-url-state/search?q=Warn&type=Issues&utf8=%E2%9C%93) and [map co-ordinates](https://www.google.com/maps/@51.4500085,-2.5916496,15z). I didn't imagine the entire state of an application living in the url.

I think the current API supports what you are suggesting:
The second argument to `withUrlState` is a function which takes the props given to the component and needs to return the initial url state.

If you are using this component with Redux and you might do something like this:

```javascript
import { history } from './appHistory'
import React from 'react'
import { connect } from 'redux'
import { withUrlState } from 'with-url-state'

const MyComponent = (props) => (...)

const mapReduxState = (state) => ({ searchOptions: state.searchOptions })

// You get the opportunity to 'map' the props into the object you want to use
// as the initial state
const getInitialUrlState = (props) => ({ 
  q: props.searchOptions.query, 
  s: 'some initial value',
})

const ConnectedComponent = 
  connect(mapReduxState)(
    withUrlState(history, getInitialUrlState)(
      MyComponent
    )
  )

export default ConnectedComponent    
```

Does that clear things up a bit?

**Comment by Dean177** [comment]
@userpixel I am going to close this, let me know if you feel like I haven't addressed your concerns.

**Comment by userpixel** [comment]
It would be great to have this warning in the README:

> if you have sensitive information in your state, it's best to black list them.

**Comment by Dean177** [comment]
The bit im not seeing is how the sensitive info gets there, by default only the bits you explicitly provide in `getInitialUrlState` end up in the url.

**Comment by userpixel** [comment]
ah, I missed that. then disregard my last comment and just emphasize what you just said (possibly on the readme).

**Comment by Dean177** [comment]
Oh great, I think the readme is lacking a section on that API, I will try to add that soon. Thanks for bringing it up @userpixel
