### ISSUE TITLE
Validation/defaults

### ISSUE THREAD

**Issue by mrclay** [Dean177/with-url-state#45]
While of course we can have a function to read props to validate, etc., it might be cleaner to allow declaring expected names/validators/defaults so you have control over what can get into props. Just an idea.

**Comment by Dean177** [comment]
Hi @mrclay 

The API for `withUrlState` forces you to provide initial values for your state, in the [color change example you can see this on the last line](https://github.com/Dean177/with-url-state/blob/master/example/src/App.tsx). I think this covers what you are suggesting with expected names / defaults.

Im not sure what you mean by validators, can you expand on that a little bit?

**Comment by mrclay** [comment]
An attacker can easily send a user to a page with arbitrary querystring, which gets injected right into props. It *should* be safe, but I wouldn't gamble on it being harmless in all apps. Hopefully no one's dumb enough to render something from props.urlState as raw markup!

**Comment by Dean177** [comment]
That's a good point, at the moment the onus is on the user to make sure that they are validating what comes in from the query param. I will have a think about if this is best handled in the docs or by adding additional features.
