### ISSUE TITLE
Confusion around initialState

### ISSUE THREAD

**Issue by mrclay** [Dean177/with-url-state#46]
Currently the API fixes the state you pass in, but it means the demo can't just load the page with `?color=red`; it always gets wiped to blue. I'd assume bookmarking state is the goal here, right?

So ideally you'd be giving the component default values to apply *if missing from the query*. Right now to apply defaults you have to leave them out of the initial state and make your own function wrapper that reads props and applies the default.

**Comment by Dean177** [comment]
Thanks, this is a bug:
https://github.com/Dean177/with-url-state/blob/bc26c48b4e5bfff87650185d3631386feffbb154/src/withUrlState.ts#L30

Is attempting to do what you are suggesting, but something isn't working correctly, I will try to look into this later.

**Comment by Dean177** [comment]
This should now be resolved and i have released [v1.2.1](https://github.com/Dean177/with-url-state/releases/tag/v1.2.1)
