### ISSUE TITLE
Suggestion: Use the state to be pushed instead of what is called by setUrlState

### ISSUE THREAD

**Issue by MGHawes** [Dean177/with-url-state#97]
https://github.com/Dean177/with-url-state/blob/a6d1250eaba7cb97863159a7ea62f025c891131a/src/withUrlState.ts#L127
```
config &&
config.shouldPushState &&
config.shouldPushState(this.props, newState, parse(this.state.previousSearch))
 ? history.push(nextLocation)
 : history.replace(nextLocation)
```

@Dean177 Might be better to have `shouldPushState` called with the merge of `newState` and `currentState` otherwise it's a bit hard to compare them.
Example: Suppose your state is `{ a: 1, b: 2 }` and you call `setUrlState({ a: 3 })`. I would expect a call of:
```
shouldPushState(props, { a: 3, b: 2 }, { a: 1, b: 2 })
```
not
```
shouldPushState(props, { a: 3 }, { a: 1, b: 2 })
```
Thoughts?

I can obviously work around this if you think that's a worse API but I reckon it makes sense. At the very least if we keep it the same we should rename `newState` to something like `stateUpdate` or something. I don't mind making a quick PR?

**Comment by Dean177** [comment]
I agree, a PR would be great
